language: csharp

solution: POSL/POSL.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore POSL/POSL.sln

script:
  - xbuild ./POSL/POSL.sln
  - nunit-console ./POSL/POSL_Test/bin/Debug/POSL_Test.dll
